#!/bin/bash

# Usage:
# qsub job_sawtooth

#PBS -l select=1:ncpus=48:mpiprocs=24
#PBS -l walltime=50:00:00
#PBS -m ae
#PBS -N cardinal
#PBS -j oe
#PBS -P moose

module purge
module load use.moose
module load moose-tools
module load openmpi/4.1.5_ucx1.14.1
module load cmake/3.27.7-oneapi-2023.2.1-4uzb

# Revise for your repository location
export CARDINAL_DIR=$HOME/cardinal_new/cardinal

export NEKRS_HOME=$HOME/cardinal_new/cardinal/install

#run NekRS
cd /home/hegaaya/homogenous_vs_hetrogenous/40cases/40_power2/homog/
rm logfile

#mpirun --n-threads=4 
$CARDINAL_DIR/cardinal-opt -i common_input.i openmc.i --n-threads=24 > logfile
